name=FAAC
version=2.1.0
author=Fabian Greffrath, Menno Bakker, Krzysztof Nikiel, Dan Villiom P. Christiansen, Nils Schimmelmann
maintainer=Nils Schimmelmann
sentence=MPEG-4 AAC-LC and HE-AAC v1 audio encoder library.
paragraph=FAAC is an open-source, dependency-free AAC audio encoder aimed at embedded and IoT applications (such as ESP32 and RP2040/RP2350 Raspberry Pi Pico) where memory footprint and encoding throughput matter.
category=Data Processing
url=https://github.com/knik/faac
architectures=esp32,rp2040,samd,stm32,*
includes=faac.h
