name: WASM Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y meson ninja-build

      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Build FAAC WASM via Meson
        run: |
          meson setup build-wasm --default-library=static --cross-file frontend/emscripten.cross -Dfloating-point=single -Dfrontend=true
          ninja -C build-wasm

      - name: Prepare Artifacts
        run: |
          mkdir -p dist
          cp frontend/index.html frontend/worker.js build-wasm/frontend/faac.js build-wasm/frontend/faac.wasm dist/
          cp frontend/faac.ico dist/favicon.ico
          zip -r faac-wasm.zip dist/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: faac-wasm
          path: faac-wasm.zip

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
